Sprint6
ClevertecFrontendLab/Andrewww1337 pull request #4
Opened 2023-03-17 15:57 UTC by Andrewww1337

2023-03-17 16:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 16:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 52%.
Общее количество тестов: 25.
Количество непройденных тестов: 12.

2023-03-17 16:18 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 16:50 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 17:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 18:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 20:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 20:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 20:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 20:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 72%.
Общее количество тестов: 25.
Количество непройденных тестов: 7.

2023-03-17 21:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 21:58 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 25.
Количество непройденных тестов: 10.

2023-03-17 22:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 25.
Количество непройденных тестов: 0.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/9-today-is-sunday.png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679093384/edit-mobile-view.png)

2023-03-18 07:15 UTC, Ivan6813 requested changes

2023-03-18 07:15 UTC, Ivan6813 commented on src/components/calendar/hooks/use-calendar.js
> +  const [mode, setMode] = React.useState('days');
а просто добавить в импорты useState `import React, { useCallback, useState  } from 'react';` не работает?

2023-03-18 07:15 UTC, Ivan6813 commented on src/components/calendar/hooks/use-calendar.js
> +  const days = React.useMemo(() => selectedMonth.createMonthDays(), [selectedMonth]);
и useMemo так же можно добавить в импорты и не писать React каждый раз

2023-03-18 07:15 UTC, Ivan6813 commented on src/components/success-booking/success-booking.jsx
> +          <p>Бронирование книги успешно отменено!</p>
очень много сложных условий у тебя) надо упрощать

2023-03-18 09:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 25.
Количество непройденных тестов: 0.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/9-today-is-sunday.png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Andrewww1337/1679132716/edit-mobile-view.png)

2023-03-18 10:09 UTC, Ivan6813 approved these changes

2023-03-18 10:44 UTC, merged